from thomaschln/r-publish

run R -e "install.packages(c('magrittr', 'data.table'))"
run R -e "source('https://bioconductor.org/biocLite.R')"
run R -e "devtools::install_github('genometra/SNPediaR/pkg')"
run R -e "install.packages(c('DT', 'digest', 'flexdashboard'))"
